import { MigrationInterface, QueryRunner } from "typeorm";

export class GeneratedBaseline1710000000000 implements MigrationInterface {
    name = 'GeneratedBaseline1710000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
        if (await queryRunner.hasTable('users')) return;
        await queryRunner.query(`CREATE TYPE "public"."departments_type_enum" AS ENUM('BROKERAGE', 'SUPPLY', 'WASTAGE', 'FRESH_CHICKEN_SHOP')`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "type" "public"."departments_type_enum" NOT NULL, "head_name" character varying(100), "cost_center" character varying(50), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_8681da666ad9699d568b3e91064" UNIQUE ("name"), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."parties_party_type_enum" AS ENUM('farm', 'broker', 'shop_owner', 'customer', 'factory', 'internal_department')`);
        await queryRunner.query(`CREATE TABLE "parties" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "party_type" "public"."parties_party_type_enum" NOT NULL, "name" character varying(150) NOT NULL, "phone" character varying(30), "address" character varying(255), "linked_department_id" uuid, "primary_department_id" uuid, "opening_balance" numeric(14,2) NOT NULL DEFAULT '0', "notes" text, CONSTRAINT "UQ_2ad73c609fffcd0b73d10473651" UNIQUE ("name"), CONSTRAINT "PK_da698299dca60d55f0050dde935" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."wastage_sales_payment_method_enum" AS ENUM('cash', 'bank', 'credit')`);
        await queryRunner.query(`CREATE TABLE "wastage_sales" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "party_id" uuid, "quantity_kg" numeric(12,3) NOT NULL, "rate_per_kg" numeric(14,2) NOT NULL, "commission_per_kg" numeric(14,2) NOT NULL, "total_amount" numeric(14,2) NOT NULL, "payment_method" "public"."wastage_sales_payment_method_enum" NOT NULL, "amount_received" numeric(14,2) NOT NULL DEFAULT '0', "sale_date" date NOT NULL, "vehicle_id" uuid, "notes" character varying(255), CONSTRAINT "PK_356fd81c51726e2382eeaacf573" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."wastage_purchases_payment_method_enum" AS ENUM('cash', 'bank', 'credit')`);
        await queryRunner.query(`CREATE TABLE "wastage_purchases" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "party_id" uuid, "quantity_kg" numeric(12,3) NOT NULL, "rate_per_kg" numeric(14,2) NOT NULL, "total_amount" numeric(14,2) NOT NULL, "payment_method" "public"."wastage_purchases_payment_method_enum" NOT NULL, "amount_paid" numeric(14,2) NOT NULL DEFAULT '0', "purchase_date" date NOT NULL, "vehicle_id" uuid, "notes" character varying(255), CONSTRAINT "PK_e34ad0f0f655f3c22ff9f1308be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."vehicle_fuel_logs_payment_method_enum" AS ENUM('cash', 'bank')`);
        await queryRunner.query(`CREATE TABLE "vehicle_fuel_logs" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "fuel_date" date NOT NULL, "liters" numeric(8,2) NOT NULL, "rate_per_liter" numeric(10,2) NOT NULL, "total_amount" numeric(12,2) NOT NULL, "odometer_reading" numeric(10,1), "payment_method" "public"."vehicle_fuel_logs_payment_method_enum" NOT NULL, "notes" character varying, CONSTRAINT "PK_41fbcf028c90599f549fc2e518d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."vehicle_maintenance_logs_payment_method_enum" AS ENUM('cash', 'bank')`);
        await queryRunner.query(`CREATE TABLE "vehicle_maintenance_logs" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "maintenance_date" date NOT NULL, "maintenance_type" character varying NOT NULL, "description" character varying, "cost" numeric(12,2) NOT NULL, "vendor_name" character varying, "payment_method" "public"."vehicle_maintenance_logs_payment_method_enum" NOT NULL, CONSTRAINT "PK_eae5995bd147376bb61d984bc81" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_vehicle_type_enum" AS ENUM('truck', 'van', 'car', 'motorcycle', 'other')`);
        await queryRunner.query(`CREATE TABLE "vehicles" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "registration_number" character varying NOT NULL, "vehicle_type" "public"."vehicles_vehicle_type_enum" NOT NULL, "model" character varying NOT NULL, "year" integer NOT NULL, "department_id" uuid NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_2abf18fae2b9477bc1927675311" UNIQUE ("registration_number"), CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "permission_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_01f4295968ba33d73926684264f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "resource" character varying, "action" character varying, CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_id" uuid, "permission_id" uuid, CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "full_name" character varying NOT NULL, "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "phone" character varying, "role_id" uuid, "department_id" uuid, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."supply_sales_payment_method_enum" AS ENUM('cash', 'bank', 'credit')`);
        await queryRunner.query(`CREATE TABLE "supply_sales" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "party_id" uuid, "quantity_kg" numeric(12,3) NOT NULL, "rate_per_kg" numeric(14,2) NOT NULL, "commission_per_kg" numeric(14,2) NOT NULL, "total_amount" numeric(14,2) NOT NULL, "payment_method" "public"."supply_sales_payment_method_enum" NOT NULL, "amount_received" numeric(14,2) NOT NULL DEFAULT '0', "sale_date" date NOT NULL, "vehicle_id" uuid, "notes" character varying(255), CONSTRAINT "PK_762c89205dc473c2d6631fb50cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."supply_purchases_payment_method_enum" AS ENUM('cash', 'bank', 'credit')`);
        await queryRunner.query(`CREATE TABLE "supply_purchases" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "party_id" uuid, "quantity_kg" numeric(12,3) NOT NULL, "rate_per_kg" numeric(14,2) NOT NULL, "total_amount" numeric(14,2) NOT NULL, "payment_method" "public"."supply_purchases_payment_method_enum" NOT NULL, "amount_paid" numeric(14,2) NOT NULL DEFAULT '0', "purchase_date" date NOT NULL, "vehicle_id" uuid, "notes" character varying(255), CONSTRAINT "PK_2d9115ae62ca780c51c7114fc54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."internal_transfers_settlement_status_enum" AS ENUM('unsettled', 'partially_settled', 'settled')`);
        await queryRunner.query(`CREATE TABLE "internal_transfers" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "from_department_id" uuid NOT NULL, "to_department_id" uuid NOT NULL, "quantity_kg" numeric(12,3) NOT NULL, "internal_rate_per_kg" numeric(14,2) NOT NULL, "total_amount" numeric(14,2) NOT NULL, "settlement_status" "public"."internal_transfers_settlement_status_enum" NOT NULL DEFAULT 'unsettled', "amount_settled" numeric(14,2) NOT NULL DEFAULT '0', "transfer_date" date NOT NULL, "vehicle_id" uuid, "notes" character varying(255), CONSTRAINT "PK_9bb038198b7b7afd8c532d54ddc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."party_payments_direction_enum" AS ENUM('received', 'paid')`);
        await queryRunner.query(`CREATE TYPE "public"."party_payments_payment_method_enum" AS ENUM('cash', 'bank')`);
        await queryRunner.query(`CREATE TABLE "party_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "party_id" uuid NOT NULL, "department_id" uuid NOT NULL, "amount" numeric(14,2) NOT NULL, "direction" "public"."party_payments_direction_enum" NOT NULL, "payment_method" "public"."party_payments_payment_method_enum" NOT NULL, "payment_date" date NOT NULL, "notes" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_87a4e6817f01e358b8e6c033b5a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d011c6945435ce00d5df272c05" ON "party_payments" ("party_id", "payment_date") `);
        await queryRunner.query(`CREATE TYPE "public"."chart_of_accounts_code_enum" AS ENUM('cash', 'bank', 'accounts_receivable', 'accounts_payable', 'revenue', 'cogs', 'operating_expense', 'payroll_expense', 'employee_advance')`);
        await queryRunner.query(`CREATE TYPE "public"."chart_of_accounts_account_nature_enum" AS ENUM('asset', 'liability', 'income', 'expense')`);
        await queryRunner.query(`CREATE TABLE "chart_of_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" "public"."chart_of_accounts_code_enum" NOT NULL, "name" character varying(100) NOT NULL, "account_nature" "public"."chart_of_accounts_account_nature_enum" NOT NULL, CONSTRAINT "UQ_e739f9fb242a95d501aedde46c8" UNIQUE ("code"), CONSTRAINT "PK_467c08a2efc78393c647da32bac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ledger_entries_entry_type_enum" AS ENUM('debit', 'credit')`);
        await queryRunner.query(`CREATE TYPE "public"."ledger_entries_source_type_enum" AS ENUM('purchase', 'sale', 'internal_transfer', 'payment', 'expense', 'salary', 'advance', 'bonus', 'stock_writeoff', 'opening_balance')`);
        await queryRunner.query(`CREATE TABLE "ledger_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "account_id" uuid NOT NULL, "party_id" uuid, "entry_type" "public"."ledger_entries_entry_type_enum" NOT NULL, "amount" numeric(14,2) NOT NULL, "entry_date" date NOT NULL, "source_type" "public"."ledger_entries_source_type_enum" NOT NULL, "source_id" uuid NOT NULL, "description" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, CONSTRAINT "PK_6efcb84411d3f08b08450ae75d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_56d4ec1e72c9ea291b169ab584" ON "ledger_entries" ("source_type", "source_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_239dbb35ab9a1d31c69cb3ec3d" ON "ledger_entries" ("party_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_284a4f5d9aa347a3bf7ab2608b" ON "ledger_entries" ("department_id", "entry_date") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_movement_type_enum" AS ENUM('purchase_in', 'sale_out', 'transfer_in', 'transfer_out', 'writeoff_out', 'opening_stock')`);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_source_type_enum" AS ENUM('purchase', 'sale', 'internal_transfer', 'stock_writeoff', 'opening_balance')`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "movement_type" "public"."stock_movements_movement_type_enum" NOT NULL, "quantity_kg" numeric(12,3) NOT NULL, "rate_per_kg" numeric(14,2) NOT NULL, "resulting_wac" numeric(14,2) NOT NULL, "source_type" "public"."stock_movements_source_type_enum" NOT NULL, "source_id" uuid NOT NULL, "movement_date" date NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c8c3d90aa60561a2af40881077" ON "stock_movements" ("source_type", "source_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e61c752d995953119731e59655" ON "stock_movements" ("department_id", "movement_date") `);
        await queryRunner.query(`CREATE TABLE "batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid, "batch_code" character varying, CONSTRAINT "PK_55e7ff646e969b61d37eea5be7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."temperature_logs_status_enum" AS ENUM('NORMAL', 'WARNING', 'CRITICAL')`);
        await queryRunner.query(`CREATE TABLE "temperature_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stock_movement_id" uuid, "batch_id" uuid, "recorded_temp" numeric(5,2) NOT NULL, "threshold" numeric(5,2) NOT NULL, "status" "public"."temperature_logs_status_enum" NOT NULL, "recorded_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7738b8501fbf3aa21698f99a34f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stock_writeoffs_reason_enum" AS ENUM('spoilage', 'mortality', 'transit_loss', 'other')`);
        await queryRunner.query(`CREATE TABLE "stock_writeoffs" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "quantity_kg" numeric(12,3) NOT NULL, "reason" "public"."stock_writeoffs_reason_enum" NOT NULL, "note" character varying(255), "writeoff_date" date NOT NULL, "valuation_amount" numeric(14,2) NOT NULL, CONSTRAINT "PK_8d4ae55e5e2a73eddc7be7336ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "department_id" uuid NOT NULL, "quantity_kg" numeric(12,3) NOT NULL DEFAULT '0', "wac" numeric(14,2) NOT NULL DEFAULT '0', CONSTRAINT "UQ_3e52924e83de23db3f163d91161" UNIQUE ("department_id"), CONSTRAINT "PK_4c0d249ce58f9a559eb7df31b23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."quality_inspections_status_enum" AS ENUM('PASSED', 'FAILED', 'CONDITIONAL')`);
        await queryRunner.query(`CREATE TABLE "quality_inspections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "batch_id" uuid NOT NULL, "inspector_user_id" uuid NOT NULL, "status" "public"."quality_inspections_status_enum" NOT NULL, "remarks" character varying, "inspected_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_95d9caed0d2abaff779a8fd4300" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shop_sales_payment_method_enum" AS ENUM('cash', 'bank', 'credit')`);
        await queryRunner.query(`CREATE TABLE "shop_sales" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "customer_party_id" uuid, "quantity_kg" numeric(12,3) NOT NULL, "rate_per_kg" numeric(14,2) NOT NULL, "profit_margin_per_kg" numeric(14,2) NOT NULL, "total_amount" numeric(14,2) NOT NULL, "payment_method" "public"."shop_sales_payment_method_enum" NOT NULL, "amount_received" numeric(14,2) NOT NULL DEFAULT '0', "sale_date" date NOT NULL, "notes" character varying(255), CONSTRAINT "PK_4b56b8a67d5564aaebc5b7b5dbf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."expense_categories_category_type_enum" AS ENUM('operational', 'maintenance', 'transport', 'administrative', 'miscellaneous')`);
        await queryRunner.query(`CREATE TABLE "expense_categories" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "category_type" "public"."expense_categories_category_type_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "is_system_generated" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_6bdb3db95dd955d3c701e935426" UNIQUE ("name"), CONSTRAINT "PK_d0ef31e189d9523461215b62775" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "expenses" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "category_id" uuid NOT NULL, "amount" numeric(14,2) NOT NULL, "expense_date" date NOT NULL, "description" character varying(255), "receipt_reference" character varying(100), "is_approved" boolean NOT NULL DEFAULT false, "approved_by" uuid, "approved_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employees" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "department_id" uuid, "employee_code" character varying(100), "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "email" character varying(255), "phone_number" character varying(50), "monthly_salary" numeric(14,2), "daily_wage" numeric(14,2), "status" character varying(50) NOT NULL DEFAULT 'active', "join_date" date, "separation_date" date, "is_active" boolean NOT NULL DEFAULT true, "address" text, CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."salary_runs_payment_status_enum" AS ENUM('pending', 'paid')`);
        await queryRunner.query(`CREATE TYPE "public"."salary_runs_payment_method_enum" AS ENUM('cash', 'bank')`);
        await queryRunner.query(`CREATE TABLE "salary_runs" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employee_id" uuid NOT NULL, "period_month" smallint NOT NULL, "period_year" smallint NOT NULL, "base_salary" numeric(14,2) NOT NULL, "total_bonuses" numeric(14,2) NOT NULL DEFAULT '0', "total_advances_deducted" numeric(14,2) NOT NULL DEFAULT '0', "net_payable" numeric(14,2) NOT NULL, "payment_status" "public"."salary_runs_payment_status_enum" NOT NULL DEFAULT 'pending', "paid_date" date, "payment_method" "public"."salary_runs_payment_method_enum", CONSTRAINT "UQ_d056325b096dd8244bea5f2a5ad" UNIQUE ("employee_id", "period_month", "period_year"), CONSTRAINT "PK_c7f453246f4cf5f3e50d4fde337" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employee_bonuses" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employee_id" uuid NOT NULL, "amount" numeric(14,2) NOT NULL, "bonus_date" date NOT NULL, "reason" text, CONSTRAINT "PK_e6ce056c512e1fcaefc99765874" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."employee_advances_recovery_status_enum" AS ENUM('outstanding', 'partially_recovered', 'fully_recovered')`);
        await queryRunner.query(`CREATE TABLE "employee_advances" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employee_id" uuid NOT NULL, "amount" numeric(14,2) NOT NULL, "advance_date" date NOT NULL, "reason" text, "recovery_status" "public"."employee_advances_recovery_status_enum" NOT NULL DEFAULT 'outstanding', "amount_recovered" numeric(14,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_67088453c94606fff3f287671a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_type_enum" AS ENUM('CREATE', 'UPDATE', 'DELETE', 'POST', 'REVERSE', 'APPROVE', 'REJECT', 'VIEW')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_status_enum" AS ENUM('SUCCESS', 'FAILURE')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "entity_type" character varying NOT NULL, "entity_id" character varying NOT NULL, "action_type" "public"."audit_logs_action_type_enum" NOT NULL, "old_values" text, "new_values" text, "description" character varying, "ip_address" character varying, "session_id" character varying, "user_agent" character varying, "status" "public"."audit_logs_status_enum" NOT NULL, "error_message" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_e14a28762f35f8b2b03a570566" ON "audit_logs" ("user_id", "action_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."attachments_document_type_enum" AS ENUM('INVOICE', 'RECEIPT', 'VOUCHER', 'PROOF', 'NOTE', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "parent_type" character varying NOT NULL, "parent_id" character varying NOT NULL, "file_name" character varying NOT NULL, "file_url" character varying NOT NULL, "mime_type" character varying, "file_size" bigint, "uploaded_by" character varying, "description" character varying, "document_type" "public"."attachments_document_type_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."approval_workflows_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."approval_workflows_approval_level_enum" AS ENUM('PENDING_APPROVAL', 'AUTO_APPROVED', 'FORCE_POSTED')`);
        await queryRunner.query(`CREATE TABLE "approval_workflows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entity_type" character varying NOT NULL, "entity_id" character varying NOT NULL, "creator_user_id" character varying NOT NULL, "approver_user_id" character varying, "status" "public"."approval_workflows_status_enum" NOT NULL, "approval_date" date, "approval_notes" character varying, "rejection_reason" character varying, "approval_level" "public"."approval_workflows_approval_level_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f326145fd927565de30b360264b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9d66a8482979f1285f0a5c15a0" ON "approval_workflows" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8fd7104494c842e556581db86" ON "approval_workflows" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."brokerage_sales_payment_method_enum" AS ENUM('cash', 'credit')`);
        await queryRunner.query(`CREATE TABLE "brokerage_sales" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "party_id" uuid, "quantity_kg" numeric(12,3) NOT NULL, "rate_per_kg" numeric(14,2) NOT NULL, "total_amount" numeric(14,2) NOT NULL, "commission_per_kg" numeric(14,2) NOT NULL, "commission_amount" numeric(14,2) NOT NULL, "payment_method" "public"."brokerage_sales_payment_method_enum" NOT NULL, "sale_date" date NOT NULL, "description" character varying(255), CONSTRAINT "PK_5fd48c89fe8d542e3a82e0c9886" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."brokerage_purchases_payment_method_enum" AS ENUM('cash', 'credit')`);
        await queryRunner.query(`CREATE TABLE "brokerage_purchases" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "party_id" uuid, "quantity_kg" numeric(12,3) NOT NULL, "rate_per_kg" numeric(14,2) NOT NULL, "total_amount" numeric(14,2) NOT NULL, "payment_method" "public"."brokerage_purchases_payment_method_enum" NOT NULL, "purchase_date" date NOT NULL, "description" character varying(255), CONSTRAINT "PK_04371138be29fadd0b6268ec545" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "user_id" uuid NOT NULL, "expires_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "is_revoked" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "parties" ADD CONSTRAINT "FK_76b7d0e012aef5d1ae55dd4b26f" FOREIGN KEY ("linked_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parties" ADD CONSTRAINT "FK_1d34bdecc5b3b0b381784e8d9e4" FOREIGN KEY ("primary_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wastage_sales" ADD CONSTRAINT "FK_7adafbd50a74197ba325bf27412" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wastage_sales" ADD CONSTRAINT "FK_87053eefb8086d81bd0fcc9bc19" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wastage_purchases" ADD CONSTRAINT "FK_eaf593d97abef0d32473c9be269" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wastage_purchases" ADD CONSTRAINT "FK_147312ddf72cef578a2405a7d7b" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_fuel_logs" ADD CONSTRAINT "FK_9558044ea780da7a580ba275e2f" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_maintenance_logs" ADD CONSTRAINT "FK_9e51fce4713ac9709a289352d63" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_292c9698ee7dd17e99fb519ef94" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permissions" ADD CONSTRAINT "FK_3495bd31f1862d02931e8e8d2e8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permissions" ADD CONSTRAINT "FK_8145f5fadacd311693c15e41f10" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_0921d1972cf861d568f5271cd85" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supply_sales" ADD CONSTRAINT "FK_3aa8c7a5cefd055d59ef7aaae90" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supply_sales" ADD CONSTRAINT "FK_d4fd6aee003ff5351852872da40" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supply_purchases" ADD CONSTRAINT "FK_01d57387bcdec139d9f514c4ae8" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supply_purchases" ADD CONSTRAINT "FK_91e9bf92649433c2c4613794a2a" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "internal_transfers" ADD CONSTRAINT "FK_49e1c364ab06e5e0719273f4da2" FOREIGN KEY ("from_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "internal_transfers" ADD CONSTRAINT "FK_970a0a0397196d5bcf8ebec8642" FOREIGN KEY ("to_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD CONSTRAINT "FK_663d09f8bde8ac38abc9c77fc77" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD CONSTRAINT "FK_e4440167e470be69f9622c1ceab" FOREIGN KEY ("account_id") REFERENCES "chart_of_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD CONSTRAINT "FK_239dbb35ab9a1d31c69cb3ec3d2" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_f702d9df01e5454f33bfce95253" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temperature_logs" ADD CONSTRAINT "FK_42c96a00a69399ac711e8e7920b" FOREIGN KEY ("stock_movement_id") REFERENCES "stock_movements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temperature_logs" ADD CONSTRAINT "FK_8d8533caa2ed5a629453287144e" FOREIGN KEY ("batch_id") REFERENCES "batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_writeoffs" ADD CONSTRAINT "FK_0c74fddf211738e9118093395ff" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quality_inspections" ADD CONSTRAINT "FK_13f7c4be285e491f5dcbcc2701a" FOREIGN KEY ("batch_id") REFERENCES "batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quality_inspections" ADD CONSTRAINT "FK_462067d42c68e55108c6244cc39" FOREIGN KEY ("inspector_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_sales" ADD CONSTRAINT "FK_d9e431543e06da1a3b83148908b" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_sales" ADD CONSTRAINT "FK_c73aefa872f7c8d4c4dd6a5ea26" FOREIGN KEY ("customer_party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_8584bd4e29c79615ceb5062da83" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_5d1f4be708e0dfe2afa1a3c376c" FOREIGN KEY ("category_id") REFERENCES "expense_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_2d83c53c3e553a48dadb9722e38" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_678a3540f843823784b0fe4a4f2" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_runs" ADD CONSTRAINT "FK_0d6cbd57a3b37d842227a6507be" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_bonuses" ADD CONSTRAINT "FK_c72ec59163221ece35a784ddc63" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_advances" ADD CONSTRAINT "FK_a90096aef5ac32f28cae96ef252" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brokerage_sales" ADD CONSTRAINT "FK_d04fb8b0a05d1f9039e69fa600d" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brokerage_sales" ADD CONSTRAINT "FK_68f9782bd95a21f90504d2d439c" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brokerage_purchases" ADD CONSTRAINT "FK_3be2d60915bcd5c47c6439cd5e0" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brokerage_purchases" ADD CONSTRAINT "FK_dc1873a3ff825625e4bb25362f7" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "brokerage_purchases" DROP CONSTRAINT "FK_dc1873a3ff825625e4bb25362f7"`);
        await queryRunner.query(`ALTER TABLE "brokerage_purchases" DROP CONSTRAINT "FK_3be2d60915bcd5c47c6439cd5e0"`);
        await queryRunner.query(`ALTER TABLE "brokerage_sales" DROP CONSTRAINT "FK_68f9782bd95a21f90504d2d439c"`);
        await queryRunner.query(`ALTER TABLE "brokerage_sales" DROP CONSTRAINT "FK_d04fb8b0a05d1f9039e69fa600d"`);
        await queryRunner.query(`ALTER TABLE "employee_advances" DROP CONSTRAINT "FK_a90096aef5ac32f28cae96ef252"`);
        await queryRunner.query(`ALTER TABLE "employee_bonuses" DROP CONSTRAINT "FK_c72ec59163221ece35a784ddc63"`);
        await queryRunner.query(`ALTER TABLE "salary_runs" DROP CONSTRAINT "FK_0d6cbd57a3b37d842227a6507be"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_678a3540f843823784b0fe4a4f2"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_2d83c53c3e553a48dadb9722e38"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_5d1f4be708e0dfe2afa1a3c376c"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_8584bd4e29c79615ceb5062da83"`);
        await queryRunner.query(`ALTER TABLE "shop_sales" DROP CONSTRAINT "FK_c73aefa872f7c8d4c4dd6a5ea26"`);
        await queryRunner.query(`ALTER TABLE "shop_sales" DROP CONSTRAINT "FK_d9e431543e06da1a3b83148908b"`);
        await queryRunner.query(`ALTER TABLE "quality_inspections" DROP CONSTRAINT "FK_462067d42c68e55108c6244cc39"`);
        await queryRunner.query(`ALTER TABLE "quality_inspections" DROP CONSTRAINT "FK_13f7c4be285e491f5dcbcc2701a"`);
        await queryRunner.query(`ALTER TABLE "stock_writeoffs" DROP CONSTRAINT "FK_0c74fddf211738e9118093395ff"`);
        await queryRunner.query(`ALTER TABLE "temperature_logs" DROP CONSTRAINT "FK_8d8533caa2ed5a629453287144e"`);
        await queryRunner.query(`ALTER TABLE "temperature_logs" DROP CONSTRAINT "FK_42c96a00a69399ac711e8e7920b"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_f702d9df01e5454f33bfce95253"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP CONSTRAINT "FK_239dbb35ab9a1d31c69cb3ec3d2"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP CONSTRAINT "FK_e4440167e470be69f9622c1ceab"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP CONSTRAINT "FK_663d09f8bde8ac38abc9c77fc77"`);
        await queryRunner.query(`ALTER TABLE "internal_transfers" DROP CONSTRAINT "FK_970a0a0397196d5bcf8ebec8642"`);
        await queryRunner.query(`ALTER TABLE "internal_transfers" DROP CONSTRAINT "FK_49e1c364ab06e5e0719273f4da2"`);
        await queryRunner.query(`ALTER TABLE "supply_purchases" DROP CONSTRAINT "FK_91e9bf92649433c2c4613794a2a"`);
        await queryRunner.query(`ALTER TABLE "supply_purchases" DROP CONSTRAINT "FK_01d57387bcdec139d9f514c4ae8"`);
        await queryRunner.query(`ALTER TABLE "supply_sales" DROP CONSTRAINT "FK_d4fd6aee003ff5351852872da40"`);
        await queryRunner.query(`ALTER TABLE "supply_sales" DROP CONSTRAINT "FK_3aa8c7a5cefd055d59ef7aaae90"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_0921d1972cf861d568f5271cd85"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "user_permissions" DROP CONSTRAINT "FK_8145f5fadacd311693c15e41f10"`);
        await queryRunner.query(`ALTER TABLE "user_permissions" DROP CONSTRAINT "FK_3495bd31f1862d02931e8e8d2e8"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_292c9698ee7dd17e99fb519ef94"`);
        await queryRunner.query(`ALTER TABLE "vehicle_maintenance_logs" DROP CONSTRAINT "FK_9e51fce4713ac9709a289352d63"`);
        await queryRunner.query(`ALTER TABLE "vehicle_fuel_logs" DROP CONSTRAINT "FK_9558044ea780da7a580ba275e2f"`);
        await queryRunner.query(`ALTER TABLE "wastage_purchases" DROP CONSTRAINT "FK_147312ddf72cef578a2405a7d7b"`);
        await queryRunner.query(`ALTER TABLE "wastage_purchases" DROP CONSTRAINT "FK_eaf593d97abef0d32473c9be269"`);
        await queryRunner.query(`ALTER TABLE "wastage_sales" DROP CONSTRAINT "FK_87053eefb8086d81bd0fcc9bc19"`);
        await queryRunner.query(`ALTER TABLE "wastage_sales" DROP CONSTRAINT "FK_7adafbd50a74197ba325bf27412"`);
        await queryRunner.query(`ALTER TABLE "parties" DROP CONSTRAINT "FK_1d34bdecc5b3b0b381784e8d9e4"`);
        await queryRunner.query(`ALTER TABLE "parties" DROP CONSTRAINT "FK_76b7d0e012aef5d1ae55dd4b26f"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "brokerage_purchases"`);
        await queryRunner.query(`DROP TYPE "public"."brokerage_purchases_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "brokerage_sales"`);
        await queryRunner.query(`DROP TYPE "public"."brokerage_sales_payment_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8fd7104494c842e556581db86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d66a8482979f1285f0a5c15a0"`);
        await queryRunner.query(`DROP TABLE "approval_workflows"`);
        await queryRunner.query(`DROP TYPE "public"."approval_workflows_approval_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."approval_workflows_status_enum"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP TYPE "public"."attachments_document_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e14a28762f35f8b2b03a570566"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_type_enum"`);
        await queryRunner.query(`DROP TABLE "employee_advances"`);
        await queryRunner.query(`DROP TYPE "public"."employee_advances_recovery_status_enum"`);
        await queryRunner.query(`DROP TABLE "employee_bonuses"`);
        await queryRunner.query(`DROP TABLE "salary_runs"`);
        await queryRunner.query(`DROP TYPE "public"."salary_runs_payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."salary_runs_payment_status_enum"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TABLE "expense_categories"`);
        await queryRunner.query(`DROP TYPE "public"."expense_categories_category_type_enum"`);
        await queryRunner.query(`DROP TABLE "shop_sales"`);
        await queryRunner.query(`DROP TYPE "public"."shop_sales_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "quality_inspections"`);
        await queryRunner.query(`DROP TYPE "public"."quality_inspections_status_enum"`);
        await queryRunner.query(`DROP TABLE "stock_balances"`);
        await queryRunner.query(`DROP TABLE "stock_writeoffs"`);
        await queryRunner.query(`DROP TYPE "public"."stock_writeoffs_reason_enum"`);
        await queryRunner.query(`DROP TABLE "temperature_logs"`);
        await queryRunner.query(`DROP TYPE "public"."temperature_logs_status_enum"`);
        await queryRunner.query(`DROP TABLE "batches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e61c752d995953119731e59655"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8c3d90aa60561a2af40881077"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_source_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_movement_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_284a4f5d9aa347a3bf7ab2608b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_239dbb35ab9a1d31c69cb3ec3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56d4ec1e72c9ea291b169ab584"`);
        await queryRunner.query(`DROP TABLE "ledger_entries"`);
        await queryRunner.query(`DROP TYPE "public"."ledger_entries_source_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ledger_entries_entry_type_enum"`);
        await queryRunner.query(`DROP TABLE "chart_of_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."chart_of_accounts_account_nature_enum"`);
        await queryRunner.query(`DROP TYPE "public"."chart_of_accounts_code_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d011c6945435ce00d5df272c05"`);
        await queryRunner.query(`DROP TABLE "party_payments"`);
        await queryRunner.query(`DROP TYPE "public"."party_payments_payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."party_payments_direction_enum"`);
        await queryRunner.query(`DROP TABLE "internal_transfers"`);
        await queryRunner.query(`DROP TYPE "public"."internal_transfers_settlement_status_enum"`);
        await queryRunner.query(`DROP TABLE "supply_purchases"`);
        await queryRunner.query(`DROP TYPE "public"."supply_purchases_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "supply_sales"`);
        await queryRunner.query(`DROP TYPE "public"."supply_sales_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "user_permissions"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_vehicle_type_enum"`);
        await queryRunner.query(`DROP TABLE "vehicle_maintenance_logs"`);
        await queryRunner.query(`DROP TYPE "public"."vehicle_maintenance_logs_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "vehicle_fuel_logs"`);
        await queryRunner.query(`DROP TYPE "public"."vehicle_fuel_logs_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "wastage_purchases"`);
        await queryRunner.query(`DROP TYPE "public"."wastage_purchases_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "wastage_sales"`);
        await queryRunner.query(`DROP TYPE "public"."wastage_sales_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "parties"`);
        await queryRunner.query(`DROP TYPE "public"."parties_party_type_enum"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TYPE "public"."departments_type_enum"`);
    }

}
